
DROP TABLE IF EXISTS `BA_USER`;

CREATE TABLE `BA_USER` (
  `USER_ID` varchar(200) NOT NULL,
  `TENANT_ID` bigint(20) NOT NULL,
  `CREATED_BY` varchar(75) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `MODIFIED_BY` varchar(75) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `ACCOUNT_EXPIRED` bit(1) DEFAULT NULL,
  `ACCOUNT_LOCKED` bit(1) DEFAULT NULL,
  `CREDENTIAL_EXPIRED` bit(1) DEFAULT NULL,
  `BIRTH_DATE` datetime DEFAULT NULL,
  `ACTIVE` bit(1) DEFAULT NULL,
  `EXPIRE_DATE` datetime DEFAULT NULL,
  `FAILED_COUNT` int(11) DEFAULT NULL,
  `FIRST_NAME` varchar(200) NOT NULL,
  `GENDER_CODE` varchar(255) DEFAULT NULL,
  `PHOTO` tinyblob,
  `LANGUAGE_ID` varchar(5) DEFAULT NULL,
  `LAST_LOGIN_DATE` datetime DEFAULT NULL,
  `LAST_NAME` varchar(200) NOT NULL,
  `MIDDLE_NAME` varchar(200) DEFAULT NULL,
  `IS_ONLINE` bit(1) DEFAULT NULL,
  `PASSWORD` varchar(200) NOT NULL,
  `PHONE_NUM` varchar(10) NOT NULL,
  `TERMINATION_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


