/*
SQLyog Community v10.51 
MySQL - 5.6.17 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('0','RESET_PASSWD','RESET_PASSWD','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('1','CREATE_ROLE','CREATE_ROLE','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('2','UPDATE_ROLE','UPDATE_ROLE','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('3','READ_ROLE','READ_ROLE','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('4','DELETE_ROLE','DELETE_ROLE','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('5','SEARCH_ROLE','SEARCH_ROLE','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('6','CREATE_SUPPLIER','CREATE_SUPPLIER','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('7','UPDATE_SUPPLIER','UPDATE_SUPPLIER','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('8','READ_SUPPLIER','READ_SUPPLIER','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('9','DELETE_SUPPLIER','DELETE_SUPPLIER','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('10','SEARCH_SUPPLIER','SEARCH_SUPPLIER','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('11','CREATE_USER','CREATE_USER','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('12','UPDATE_USER','UPDATE_USER','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('13','READ_USER','READ_USER','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('14','DELETE_USER','DELETE_USER','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('15','SEARCH_USER','SEARCH_USER','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('16','UPDATE_PROFILE','UPDATE_PROFILE','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('17','READ_PROFILE','READ_PROFILE','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('19','UPDATE_PSEUDO','UPDATE_PSEUDO','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('20','ADD_SEATS','ADD_SEATS','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('21','RENEW_SEATS','RENEW_SEATS','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('22','EXTEND_SUBDATE','EXTEND_SUBDATE','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('23','ENTERPRISE_PKG','ENTERPRISE_PKG','0');
insert into `BA_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `NAME`, `TYPE`) values('24','CREDIT_BUREAU','CREDIT_BUREAU','0');
